### ISSUE TITLE
run_number is not unique enough for trace_id

### ISSUE THREAD

**Issue by DavidS** [kvrhdn/gha-buildevents#16]
In some cases (rerunning?) the run_number is re-used by github, leading to broken traces:

![2020-12-11_11MS+0000_1028x491](https://user-images.githubusercontent.com/27712/101897727-e3f29a00-3ba2-11eb-86d7-8b9f2d1597a4.png)
![2020-12-11_11MS+0000_1028x513](https://user-images.githubusercontent.com/27712/101897730-e48b3080-3ba2-11eb-9d58-1e655b275046.png)

the trace_id should use the `github.run_id` instead.

Apologies, I'm just crushed with work today, otherwise I'd already have put up a PR fixing this.

**Comment by kvrhdn** [comment]
Thanks for the report, I can confirm this happens with my workflows as well.

I think we can either:
- add the run ID to the trace components, the trace ID will become: `<workflow>-<job>-<run-number>-<matrix-key>-<run ID>`
- use a completely random trace ID (a UUID for example)

I don't know if there is any drawback related to really long trace ID's, but the first feels most user friendly.

**Comment by kvrhdn** [comment]
So adding `GITHUB_RUN_ID` to the trace ID does not work, this run ID remains the same across re-runs.

This is [also documented that way](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables) 😅:


Environment variable | Description
---|---
GITHUB_RUN_ID | A unique number for each run within a repository. This number does not change if you re-run the workflow run.
GITHUB_RUN_NUMBER | A  unique number for each run of a particular workflow in a repository.  This number begins at 1 for the workflow's first run, and increments  with each new run. This number does not change if you re-run the  workflow run.

**Comment by DavidS** [comment]
> So adding `GITHUB_RUN_ID` to the trace ID does not work, this run ID remains the same across re-runs.


which is weird, given the `github.run_id` field in my screenshots is different. :man_shrugging: 
I'd be fine with replacing the whole trace_id with a uuid or the otel style random byte[] string (see https://github.com/honeycombio/buildevents/blob/a29a075b660897b8e610b5ee479015d7da930481/cmd_cmd.go#L71)

**Comment by DavidS** [comment]
god - I must be really stressed. There is no repo name in the trace-id - and we're running on 50 different repos - no wonder there're collisions. :facepalm:

**Comment by kvrhdn** [comment]
I can confirm this is fixed now. Re-running the workflow creates a unique trace id:

<img width="688" alt="Screenshot 2020-12-16 at 00 28 07" src="https://user-images.githubusercontent.com/7748404/102284981-945ef600-3f35-11eb-85c8-b269edae0f77.png">
