### ISSUE TITLE
Make BUILDEVENTS_FILE an absolute path

### ISSUE THREAD

**Issue by sargunv** [kvrhdn/gha-buildevents#38]
Often times I run a script via `buildevents cmd` in a directory other than my workspace root, but the command doesn't find the `buildevents.txt` file because the value of `$BUILDEVENTS_FILE` is `../buildevents.txt`. It should be an absolute path instead by default to allow easily using this from any working directory.

**Comment by kvrhdn** [comment]
Thanks for the report! We should be able to set this to an absolute path without much issue. We'll just have to figure out a good path.
The default value is set here: https://github.com/kvrhdn/gha-buildevents/blob/70cba094455143d466a64779533131eb1b28e105/src/buildevents.ts#L36-L37

**Comment by sargunv** [comment]
Could just replace it with `envPath = path.resolve('../buildevents.txt')`. That way we'll use the exact same path we're using now, and work just fine with custom runners with their own file structure.

I'd be happy to PR this tomorrow.
